site_name: Francisco Javier Humanez Carmona
site_url: https://franciscohumanez.github.io
theme:
 name: material
nav:
 - Practica2.1: index.md
 - Practica2.2: practica2.md
 - Practica2.3: pracitca3.md
 - Practica2.4: practica4.md
 - Practica2.5: practica5.md
 - Practica3.1: practica6.md
